// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalClientBase.Infrastructure.Data;

#nullable disable

namespace UniversalClientBase.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119043933_AddSeguimientoDinamico")]
    partial class AddSeguimientoDinamico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("UniversalClientBase.Core.Entities.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hallazgo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Lectura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonalExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProcesadaEnAutomatizacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuenta");

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("UniversalClientBase.Core.Entities.Sancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSancion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimoEstatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteUMA")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inciso")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pagada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UMAS")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cuenta");

                    b.ToTable("Sanciones");
                });
#pragma warning restore 612, 618
        }
    }
}
